import 'dart:convert';
import 'dart:io';

/// Generates defaults from an exported workspace JSON file.
Future<void> main(List<String> args) async {
  if (args.length != 2) {
    stderr.writeln(
      'Usage: dart tool/workspace_codegen.dart input.json output.dart',
    );
    exitCode = 64;
    return;
  }
  final json =
      jsonDecode(await File(args[0]).readAsString()) as Map<String, dynamic>;
  final output = File(args[1]).absolute;
  final temporary = File(
    '${output.parent.path}/generated_defaults_${pid}_${DateTime.now().microsecondsSinceEpoch}.dart',
  );
  try {
    await temporary.create(exclusive: true);
    await temporary.writeAsString(generateDefaults(json));
    for (final command in ['format', 'analyze']) {
      final result = await Process.run(Platform.resolvedExecutable, [
        command,
        temporary.path,
      ]);
      if (result.exitCode != 0) {
        throw StateError('${result.stdout}\n${result.stderr}');
      }
    }
    await temporary.rename(output.path);
  } finally {
    if (await temporary.exists()) await temporary.delete();
  }
}

String _literal(String value) => jsonEncode(value).replaceAll(r'$', r'\$');

String generateDefaults(Map<String, dynamic> state) {
  final workspaces = state['workspaces'] as List<dynamic>;
  final out = StringBuffer(
    "import './layout_tree.dart';\nimport './workspace_models.dart';\n\n",
  );
  out.writeln('/// Factory layouts generated by tool/workspace_codegen.dart.');
  out.writeln('abstract final class DefaultLayouts {');
  out.writeln('  static List<Workspace> all() => [');
  for (var i = 0; i < workspaces.length; i++) {
    out.writeln('    workspace$i(),');
  }
  out.writeln('  ];');
  for (var i = 0; i < workspaces.length; i++) {
    final ws = workspaces[i] as Map<String, dynamic>;
    out.writeln('  static Workspace workspace$i() => Workspace(');
    out.writeln(
      '    id: GridIds.next(), name: ${_literal(ws['name'] as String)},',
    );
    out.writeln('    root: ${_node(ws['root'])},');
    out.writeln('  );');
  }
  out.writeln('}');
  return out.toString();
}

String _node(dynamic value) {
  if (value == null) return 'null';
  final node = value as Map<String, dynamic>;
  if (node['type'] == 'leaf') {
    final settings = (node['settings'] as Map<String, dynamic>?) ?? {};
    final entries = settings.entries
        .map((e) => '${_literal(e.key)}: ${_literal(e.value as String)}')
        .join(', ');
    return 'LeafNode(tileId: GridIds.next(), tileType: ${_literal(node['tileType'] as String)}, settings: const {$entries})';
  }
  if (node['type'] != 'split') {
    throw const FormatException('Unknown layout node.');
  }
  final ratio = node['ratio'] as num;
  if (!ratio.isFinite || ratio <= 0 || ratio >= 1) {
    throw const FormatException('Split ratio must be between zero and one.');
  }
  return 'SplitNode(vertical: ${node['vertical'] == true}, ratio: $ratio, a: ${_node(node['a'])}, b: ${_node(node['b'])})';
}
